### ISSUE TITLE
Discord Username is off

### ISSUE THREAD

**Issue by merkoclerko** [CmdrJane/Discordium#11]
i'm not sure what i am doing wrong, but when a message is sent from discord to the server it displays a few roles before the username.

![image](https://user-images.githubusercontent.com/57376573/177687270-a2d63355-1724-44f9-b7d2-6acec32d7b53.png)

This is my config file, minus the Token and Webhook URL:  [Haste Bin](https://www.toptal.com/developers/hastebin/deyemotace.json)

**Comment by CmdrJane** [comment]
mc ver? list of mods?

**Comment by merkoclerko** [comment]
> mc ver? list of mods?

Shoot, I thought I included that line.  Must have deleted it by accident.

[modlist](https://www.toptal.com/developers/hastebin/seyeqafudu.css)
mc version: 1.19

**Comment by CmdrJane** [comment]
any chat mods/plugins?

**Comment by merkoclerko** [comment]
> 

I do not.

**Comment by CmdrJane** [comment]
im unable to reproduce it. Anyway i updated all libraries in project so try this out 
https://github.com/CmdrJane/Discordium/releases/tag/discordium-v.1.1.5%2B1.19
If problem will persist try stripping out mods by one and see if it help

**Comment by CmdrJane** [comment]
any feedback will be appreciated

**Comment by merkoclerko** [comment]
> any feedback will be appreciated

The mod is very cool, but the update did not help.  Since I was unable to find a mod that conflicted and you were unable to resolve it, I just disabled the mod for now.
