### ISSUE TITLE
[Feature request] Client Side stuff

### ISSUE THREAD

**Issue by vaporvee** [CmdrJane/Discordium#4]
maybe add something that you can copy the link code with a button or that you can press a button to join the discord. 
Also some ingame chat formatting could be cool that it looks like in discord. For example discord formating like `this` or underlined italic or bold text and maybe emojis

**Comment by CmdrJane** [comment]
I will look into this but dont expect it to happen immediately

**Comment by CmdrJane** [comment]
btw link code should be already clickable

**Comment by vaporvee** [comment]
ok yeah client support would be a giant change i don't expect anything
